# version: "1"
linters:
  enable:
    - gosec
  disable:
    - wsl

linters-settings:
  # see: v1: https://golangci-lint.run/usage/linters/#enabled-by-default
  godox:
    keywords:
      - "TODO"

# settings: (v2)
  # see: https://golangci-lint.run/usage/linters#linters-configuration

#issues:
  # see: https://golangci-lint.run/usage/configuration/#issues-configuration

output:
  # see https://golangci-lint.run/usage/configuration/#output-configuration
  print-issued-lines: false
  formats:
    - format: colored-line-number
      path: stdout

run:
  # see: https://golangci-lint.run/usage/configuration/#run-configuration
  concurrency: 8

#severity:
  # see: https://golangci-lint.run/usage/configuration/#severity-configuration

